spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sliip?severTimeZone=UTC&characterEncoding=UTF-8
    username: root
    password: Q1w2e3r41!
  jpa:
    hibernate:
      ddl-auto: create-drop